/********************************************************************
* JPetLoggerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetLoggerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetLoggerDict();
extern void G__cpp_setup_inheritanceJPetLoggerDict();
extern void G__cpp_setup_typetableJPetLoggerDict();
extern void G__cpp_setup_memvarJPetLoggerDict();
extern void G__cpp_setup_globalJPetLoggerDict();
extern void G__cpp_setup_memfuncJPetLoggerDict();
extern void G__cpp_setup_funcJPetLoggerDict();
extern void G__set_cpp_environmentJPetLoggerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetLogger.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetLoggerDictLN_string;
extern G__linked_taginfo G__JPetLoggerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetLoggerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetLoggerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetLoggerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetLoggerDictLN_JPetLogger;
extern G__linked_taginfo G__JPetLoggerDictLN_JPetLoggercLcLMessageType;

/* STUB derived class for protected member access */
