/********************************************************************
* JPetAnalysisModuleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetAnalysisModuleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetAnalysisModuleDict();
extern void G__cpp_setup_inheritanceJPetAnalysisModuleDict();
extern void G__cpp_setup_typetableJPetAnalysisModuleDict();
extern void G__cpp_setup_memvarJPetAnalysisModuleDict();
extern void G__cpp_setup_globalJPetAnalysisModuleDict();
extern void G__cpp_setup_memfuncJPetAnalysisModuleDict();
extern void G__cpp_setup_funcJPetAnalysisModuleDict();
extern void G__set_cpp_environmentJPetAnalysisModuleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetAnalysisModule.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetAnalysisModuleDictLN_TClass;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_TBuffer;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_TObject;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_TNamed;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetAnalysisModuleDictLN_JPetAnalysisModule;

/* STUB derived class for protected member access */
