//
// File generated by rootcint at Wed Mar 12 14:22:10 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JPetParamManagerDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JPetParamManagerDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JPetParamManager_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void JPetParamManager_Dictionary();
   static void *new_JPetParamManager(void *p = 0);
   static void *newArray_JPetParamManager(Long_t size, void *p);
   static void delete_JPetParamManager(void *p);
   static void deleteArray_JPetParamManager(void *p);
   static void destruct_JPetParamManager(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JPetParamManager*)
   {
      ::JPetParamManager *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::JPetParamManager),0);
      static ::ROOT::TGenericClassInfo 
         instance("JPetParamManager", "./JPetParamManager.h", 12,
                  typeid(::JPetParamManager), DefineBehavior(ptr, ptr),
                  0, &JPetParamManager_Dictionary, isa_proxy, 0,
                  sizeof(::JPetParamManager) );
      instance.SetNew(&new_JPetParamManager);
      instance.SetNewArray(&newArray_JPetParamManager);
      instance.SetDelete(&delete_JPetParamManager);
      instance.SetDeleteArray(&deleteArray_JPetParamManager);
      instance.SetDestructor(&destruct_JPetParamManager);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JPetParamManager*)
   {
      return GenerateInitInstanceLocal((::JPetParamManager*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JPetParamManager*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void JPetParamManager_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::JPetParamManager*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_JPetParamManager(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JPetParamManager : new ::JPetParamManager;
   }
   static void *newArray_JPetParamManager(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JPetParamManager[nElements] : new ::JPetParamManager[nElements];
   }
   // Wrapper around operator delete
   static void delete_JPetParamManager(void *p) {
      delete ((::JPetParamManager*)p);
   }
   static void deleteArray_JPetParamManager(void *p) {
      delete [] ((::JPetParamManager*)p);
   }
   static void destruct_JPetParamManager(void *p) {
      typedef ::JPetParamManager current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::JPetParamManager

/********************************************************
* JPetParamManagerDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJPetParamManagerDict();

extern "C" void G__set_cpp_environmentJPetParamManagerDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JPetParamManager.h");
  G__cpp_reset_tagtableJPetParamManagerDict();
}
#include <new>
extern "C" int G__cpp_dllrevJPetParamManagerDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JPetParamManager */
static int G__JPetParamManagerDict_170_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetParamManager*) G__getstructoffset())->readFile((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetParamManagerDict_170_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const JPetParamManager*) G__getstructoffset())->getTRBNumber((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetParamManagerDict_170_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const JPetParamManager*) G__getstructoffset())->getScinNumber((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetParamManagerDict_170_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const JPetParamManager*) G__getstructoffset())->getDataSize());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic default constructor
static int G__JPetParamManagerDict_170_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetParamManager *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetParamManager[n];
     } else {
       p = new((void*) gvp) JPetParamManager[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetParamManager;
     } else {
       p = new((void*) gvp) JPetParamManager;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetParamManagerDictLN_JPetParamManager));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__JPetParamManagerDict_170_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JPetParamManager* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JPetParamManager(*(JPetParamManager*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetParamManagerDictLN_JPetParamManager));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JPetParamManager G__TJPetParamManager;
static int G__JPetParamManagerDict_170_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JPetParamManager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JPetParamManager*) (soff+(sizeof(JPetParamManager)*i)))->~G__TJPetParamManager();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JPetParamManager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JPetParamManager*) (soff))->~G__TJPetParamManager();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__JPetParamManagerDict_170_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetParamManager* dest = (JPetParamManager*) G__getstructoffset();
   *dest = *(JPetParamManager*) libp->para[0].ref;
   const JPetParamManager& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JPetParamManager */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJPetParamManagerDict {
 public:
  G__Sizep2memfuncJPetParamManagerDict(): p(&G__Sizep2memfuncJPetParamManagerDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJPetParamManagerDict::*p)();
};

size_t G__get_sizep2memfuncJPetParamManagerDict()
{
  G__Sizep2memfuncJPetParamManagerDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJPetParamManagerDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJPetParamManagerDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JPetParamManager */
static void G__setup_memvarJPetParamManager(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JPetParamManagerDictLN_JPetParamManager));
   { JPetParamManager *p; p=(JPetParamManager*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"fTRBNumbers=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"fScinNumbers=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJPetParamManagerDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJPetParamManager(void) {
   /* JPetParamManager */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JPetParamManagerDictLN_JPetParamManager));
   G__memfunc_setup("readFile",796,G__JPetParamManagerDict_170_0_1, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - file_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTRBNumber",1169,G__JPetParamManagerDict_170_0_2, 105, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getScinNumber",1334,G__JPetParamManagerDict_170_0_3, 105, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDataSize",1109,G__JPetParamManagerDict_170_0_4, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   // automatic default constructor
   G__memfunc_setup("JPetParamManager", 1567, G__JPetParamManagerDict_170_0_5, (int) ('i'), G__get_linked_tagnum(&G__JPetParamManagerDictLN_JPetParamManager), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("JPetParamManager", 1567, G__JPetParamManagerDict_170_0_6, (int) ('i'), G__get_linked_tagnum(&G__JPetParamManagerDictLN_JPetParamManager), -1, 0, 1, 1, 1, 0, "u 'JPetParamManager' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JPetParamManager", 1693, G__JPetParamManagerDict_170_0_7, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__JPetParamManagerDict_170_0_8, (int) ('u'), G__get_linked_tagnum(&G__JPetParamManagerDictLN_JPetParamManager), -1, 1, 1, 1, 1, 0, "u 'JPetParamManager' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJPetParamManagerDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJPetParamManagerDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJPetParamManagerDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JPetParamManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetParamManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JPetParamManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetParamManagerDictLN_JPetParamManager = { "JPetParamManager" , 99 , -1 };
G__linked_taginfo G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJPetParamManagerDict() {
  G__JPetParamManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetParamManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JPetParamManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetParamManagerDictLN_JPetParamManager.tagnum = -1 ;
  G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJPetParamManagerDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JPetParamManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetParamManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JPetParamManagerDictLN_JPetParamManager),sizeof(JPetParamManager),-1,0,(char*)NULL,G__setup_memvarJPetParamManager,G__setup_memfuncJPetParamManager);
   G__get_linked_tagnum_fwd(&G__JPetParamManagerDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetParamManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupJPetParamManagerDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJPetParamManagerDict()");
  G__set_cpp_environmentJPetParamManagerDict();
  G__cpp_setup_tagtableJPetParamManagerDict();

  G__cpp_setup_inheritanceJPetParamManagerDict();

  G__cpp_setup_typetableJPetParamManagerDict();

  G__cpp_setup_memvarJPetParamManagerDict();

  G__cpp_setup_memfuncJPetParamManagerDict();
  G__cpp_setup_globalJPetParamManagerDict();
  G__cpp_setup_funcJPetParamManagerDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJPetParamManagerDict();
  return;
}
class G__cpp_setup_initJPetParamManagerDict {
  public:
    G__cpp_setup_initJPetParamManagerDict() { G__add_setup_func("JPetParamManagerDict",(G__incsetup)(&G__cpp_setupJPetParamManagerDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJPetParamManagerDict() { G__remove_setup_func("JPetParamManagerDict"); }
};
G__cpp_setup_initJPetParamManagerDict G__cpp_setup_initializerJPetParamManagerDict;

