//
// File generated by rootcint at Tue Mar 11 21:21:19 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JPetEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JPetEventDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JPetEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JPetEvent(void *p = 0);
   static void *newArray_JPetEvent(Long_t size, void *p);
   static void delete_JPetEvent(void *p);
   static void deleteArray_JPetEvent(void *p);
   static void destruct_JPetEvent(void *p);
   static void streamer_JPetEvent(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JPetEvent*)
   {
      ::JPetEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JPetEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JPetEvent", ::JPetEvent::Class_Version(), "./JPetEvent.h", 18,
                  typeid(::JPetEvent), DefineBehavior(ptr, ptr),
                  &::JPetEvent::Dictionary, isa_proxy, 0,
                  sizeof(::JPetEvent) );
      instance.SetNew(&new_JPetEvent);
      instance.SetNewArray(&newArray_JPetEvent);
      instance.SetDelete(&delete_JPetEvent);
      instance.SetDeleteArray(&deleteArray_JPetEvent);
      instance.SetDestructor(&destruct_JPetEvent);
      instance.SetStreamerFunc(&streamer_JPetEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JPetEvent*)
   {
      return GenerateInitInstanceLocal((::JPetEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JPetEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *JPetEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *JPetEvent::Class_Name()
{
   return "JPetEvent";
}

//______________________________________________________________________________
const char *JPetEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JPetEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int JPetEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JPetEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void JPetEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JPetEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *JPetEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JPetEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void JPetEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class JPetEvent.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TNamed::Streamer(R__b);
      R__b >> fTime;
      R__b >> fQualityOfTime;
      R__b >> fFirstHit;
      R__b >> fSecondHit;
      R__b.CheckByteCount(R__s, R__c, JPetEvent::IsA());
   } else {
      R__c = R__b.WriteVersion(JPetEvent::IsA(), kTRUE);
      TNamed::Streamer(R__b);
      R__b << fTime;
      R__b << fQualityOfTime;
      R__b << fFirstHit;
      R__b << fSecondHit;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void JPetEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JPetEvent.
      TClass *R__cl = ::JPetEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &fTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQualityOfTime", &fQualityOfTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fFirstHit", &fFirstHit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fSecondHit", &fSecondHit);
      TNamed::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_JPetEvent(void *p) {
      return  p ? new(p) ::JPetEvent : new ::JPetEvent;
   }
   static void *newArray_JPetEvent(Long_t nElements, void *p) {
      return p ? new(p) ::JPetEvent[nElements] : new ::JPetEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_JPetEvent(void *p) {
      delete ((::JPetEvent*)p);
   }
   static void deleteArray_JPetEvent(void *p) {
      delete [] ((::JPetEvent*)p);
   }
   static void destruct_JPetEvent(void *p) {
      typedef ::JPetEvent current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_JPetEvent(TBuffer &buf, void *obj) {
      ((::JPetEvent*)obj)->::JPetEvent::Streamer(buf);
   }
} // end of namespace ROOT for class ::JPetEvent

/********************************************************
* JPetEventDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJPetEventDict();

extern "C" void G__set_cpp_environmentJPetEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JPetEvent.h");
  G__cpp_reset_tagtableJPetEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevJPetEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JPetEvent */
static int G__JPetEventDict_521_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetEvent[n];
     } else {
       p = new((void*) gvp) JPetEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetEvent;
     } else {
       p = new((void*) gvp) JPetEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new JPetEvent(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, *(JPetHit*) libp->para[2].ref, *(JPetHit*) libp->para[3].ref);
   } else {
     p = new((void*) gvp) JPetEvent(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, *(JPetHit*) libp->para[2].ref, *(JPetHit*) libp->para[3].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const JPetEvent*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const JPetEvent*) G__getstructoffset())->GetQualityOfTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetEvent*) G__getstructoffset())->SetTime((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetEvent*) G__getstructoffset())->SetQualityOfTime((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetHit& obj = ((const JPetEvent*) G__getstructoffset())->GetfirstHit();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetHit& obj = ((const JPetEvent*) G__getstructoffset())->GetsecondHit();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetEvent*) G__getstructoffset())->SetHits((JPetHit*) G__int(libp->para[0]), (JPetHit*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetEvent*) G__getstructoffset())->SetFirstHit((JPetHit*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetEvent*) G__getstructoffset())->SetSecondHit((JPetHit*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JPetEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JPetEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JPetEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JPetEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetEventDict_521_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JPetEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__JPetEventDict_521_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JPetEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JPetEvent(*(JPetEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JPetEvent G__TJPetEvent;
static int G__JPetEventDict_521_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JPetEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JPetEvent*) (soff+(sizeof(JPetEvent)*i)))->~G__TJPetEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JPetEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JPetEvent*) (soff))->~G__TJPetEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__JPetEventDict_521_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetEvent* dest = (JPetEvent*) G__getstructoffset();
   *dest = *(JPetEvent*) libp->para[0].ref;
   const JPetEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JPetEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJPetEventDict {
 public:
  G__Sizep2memfuncJPetEventDict(): p(&G__Sizep2memfuncJPetEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJPetEventDict::*p)();
};

size_t G__get_sizep2memfuncJPetEventDict()
{
  G__Sizep2memfuncJPetEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJPetEventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent))) {
     JPetEvent *G__Lderived;
     G__Lderived=(JPetEvent*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent),G__get_linked_tagnum(&G__JPetEventDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent),G__get_linked_tagnum(&G__JPetEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJPetEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__JPetEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<EdgeType,float>",117,G__get_linked_tagnum(&G__JPetEventDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float>",117,G__get_linked_tagnum(&G__JPetEventDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType> >",117,G__get_linked_tagnum(&G__JPetEventDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SingleCh>",117,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > >",117,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ExtendedThreshold>",117,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetSigCh>",117,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetEventDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetEventDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__JPetEventDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JPetEvent */
static void G__setup_memvarJPetEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent));
   { JPetEvent *p; p=(JPetEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fQualityOfTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetEventDictLN_JPetHit),-1,-1,4,"fFirstHit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetEventDictLN_JPetHit),-1,-1,4,"fSecondHit=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJPetEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJPetEvent(void) {
   /* JPetEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent));
   G__memfunc_setup("JPetEvent",885,G__JPetEventDict_521_0_1, 105, G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JPetEvent",885,G__JPetEventDict_521_0_2, 105, G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent), -1, 0, 4, 1, 1, 0, 
"f - - 0 - Time f - - 0 - QualityOfTime "
"u 'JPetHit' - 1 - firstHit u 'JPetHit' - 1 - secondHit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__JPetEventDict_521_0_3, 102, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetQualityOfTime",1613,G__JPetEventDict_521_0_4, 102, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTime",699,G__JPetEventDict_521_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetQualityOfTime",1625,G__JPetEventDict_521_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - qualityOfTime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetfirstHit",1133,G__JPetEventDict_521_0_7, 117, G__get_linked_tagnum(&G__JPetEventDictLN_JPetHit), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetsecondHit",1217,G__JPetEventDict_521_0_8, 117, G__get_linked_tagnum(&G__JPetEventDictLN_JPetHit), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHits",708,G__JPetEventDict_521_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'JPetHit' - 0 - firstHit U 'JPetHit' - 0 - secondHit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFirstHit",1113,G__JPetEventDict_521_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "U 'JPetHit' - 0 - firstHit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSecondHit",1197,G__JPetEventDict_521_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "U 'JPetHit' - 0 - secondHit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__JPetEventDict_521_0_12, 85, G__get_linked_tagnum(&G__JPetEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JPetEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__JPetEventDict_521_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__JPetEventDict_521_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JPetEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__JPetEventDict_521_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JPetEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__JPetEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__JPetEventDict_521_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__JPetEventDict_521_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__JPetEventDict_521_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JPetEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__JPetEventDict_521_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__JPetEventDict_521_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JPetEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("JPetEvent", 885, G__JPetEventDict_521_0_24, (int) ('i'), G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent), -1, 0, 1, 1, 1, 0, "u 'JPetEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JPetEvent", 1011, G__JPetEventDict_521_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__JPetEventDict_521_0_26, (int) ('u'), G__get_linked_tagnum(&G__JPetEventDictLN_JPetEvent), -1, 1, 1, 1, 1, 0, "u 'JPetEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJPetEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJPetEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJPetEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JPetEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__JPetEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR = { "map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR = { "vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR = { "vector<ExtendedThreshold,allocator<ExtendedThreshold> >" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ExtendedThreshold,allocator<ExtendedThreshold> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR = { "vector<JPetSigCh,allocator<JPetSigCh> >" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetSigCh,allocator<JPetSigCh> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_JPetHit = { "JPetHit" , 99 , -1 };
G__linked_taginfo G__JPetEventDictLN_JPetEvent = { "JPetEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJPetEventDict() {
  G__JPetEventDictLN_TClass.tagnum = -1 ;
  G__JPetEventDictLN_TBuffer.tagnum = -1 ;
  G__JPetEventDictLN_TMemberInspector.tagnum = -1 ;
  G__JPetEventDictLN_TObject.tagnum = -1 ;
  G__JPetEventDictLN_TNamed.tagnum = -1 ;
  G__JPetEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JPetEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JPetEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__JPetEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__JPetEventDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR.tagnum = -1 ;
  G__JPetEventDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__JPetEventDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetEventDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR.tagnum = -1 ;
  G__JPetEventDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetEventDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR.tagnum = -1 ;
  G__JPetEventDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__JPetEventDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__JPetEventDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__JPetEventDictLN_JPetHit.tagnum = -1 ;
  G__JPetEventDictLN_JPetEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJPetEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetEventDictLN_JPetHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JPetEventDictLN_JPetEvent),sizeof(JPetEvent),-1,62720,(char*)NULL,G__setup_memvarJPetEvent,G__setup_memfuncJPetEvent);
}
extern "C" void G__cpp_setupJPetEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJPetEventDict()");
  G__set_cpp_environmentJPetEventDict();
  G__cpp_setup_tagtableJPetEventDict();

  G__cpp_setup_inheritanceJPetEventDict();

  G__cpp_setup_typetableJPetEventDict();

  G__cpp_setup_memvarJPetEventDict();

  G__cpp_setup_memfuncJPetEventDict();
  G__cpp_setup_globalJPetEventDict();
  G__cpp_setup_funcJPetEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJPetEventDict();
  return;
}
class G__cpp_setup_initJPetEventDict {
  public:
    G__cpp_setup_initJPetEventDict() { G__add_setup_func("JPetEventDict",(G__incsetup)(&G__cpp_setupJPetEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJPetEventDict() { G__remove_setup_func("JPetEventDict"); }
};
G__cpp_setup_initJPetEventDict G__cpp_setup_initializerJPetEventDict;

