/********************************************************************
* JPetSignalDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetSignalDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetSignalDict();
extern void G__cpp_setup_inheritanceJPetSignalDict();
extern void G__cpp_setup_typetableJPetSignalDict();
extern void G__cpp_setup_memvarJPetSignalDict();
extern void G__cpp_setup_globalJPetSignalDict();
extern void G__cpp_setup_memfuncJPetSignalDict();
extern void G__cpp_setup_funcJPetSignalDict();
extern void G__set_cpp_environmentJPetSignalDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetSignal.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetSignalDictLN_TClass;
extern G__linked_taginfo G__JPetSignalDictLN_TBuffer;
extern G__linked_taginfo G__JPetSignalDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetSignalDictLN_TObject;
extern G__linked_taginfo G__JPetSignalDictLN_TNamed;
extern G__linked_taginfo G__JPetSignalDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetSignalDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetSignalDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetSignalDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetSignalDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JPetSignalDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__JPetSignalDictLN_JPetSigCh;
extern G__linked_taginfo G__JPetSignalDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR;
extern G__linked_taginfo G__JPetSignalDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__JPetSignalDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetSignalDictLN_History;
extern G__linked_taginfo G__JPetSignalDictLN_ExtendedThreshold;
extern G__linked_taginfo G__JPetSignalDictLN_JPetSignal;
extern G__linked_taginfo G__JPetSignalDictLN_JPetSignalcLcLEdge;
extern G__linked_taginfo G__JPetSignalDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR;
extern G__linked_taginfo G__JPetSignalDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
