/********************************************************************
* JPetHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetHitDict();
extern void G__cpp_setup_inheritanceJPetHitDict();
extern void G__cpp_setup_typetableJPetHitDict();
extern void G__cpp_setup_memvarJPetHitDict();
extern void G__cpp_setup_globalJPetHitDict();
extern void G__cpp_setup_memfuncJPetHitDict();
extern void G__cpp_setup_funcJPetHitDict();
extern void G__set_cpp_environmentJPetHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetHitDictLN_TClass;
extern G__linked_taginfo G__JPetHitDictLN_TBuffer;
extern G__linked_taginfo G__JPetHitDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetHitDictLN_TObject;
extern G__linked_taginfo G__JPetHitDictLN_TNamed;
extern G__linked_taginfo G__JPetHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetHitDictLN_JPetBarrelSlot;
extern G__linked_taginfo G__JPetHitDictLN_JPetScin;
extern G__linked_taginfo G__JPetHitDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JPetHitDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__JPetHitDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR;
extern G__linked_taginfo G__JPetHitDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__JPetHitDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetHitDictLN_JPetSignal;
extern G__linked_taginfo G__JPetHitDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR;
extern G__linked_taginfo G__JPetHitDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetHitDictLN_JPetTSlot;
extern G__linked_taginfo G__JPetHitDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR;
extern G__linked_taginfo G__JPetHitDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__JPetHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__JPetHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__JPetHitDictLN_TVector3;
extern G__linked_taginfo G__JPetHitDictLN_JPetHit;
extern G__linked_taginfo G__JPetHitDictLN_JPetHitcLcLSignal;

/* STUB derived class for protected member access */
