//
// File generated by rootcint at Wed Mar 12 14:22:19 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JPetWriterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JPetWriterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* JPetWriterDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJPetWriterDict();

extern "C" void G__set_cpp_environmentJPetWriterDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JPetWriter.h");
  G__cpp_reset_tagtableJPetWriterDict();
}
#include <new>
extern "C" int G__cpp_dllrevJPetWriterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JPetWriter */
static int G__JPetWriterDict_606_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetBarrelSlot*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetBarrelSlot,allocator<JPetBarrelSlot> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetEvent*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetEvent,allocator<JPetEvent> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetHit*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetHit,allocator<JPetHit> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetPM*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetPM,allocator<JPetPM> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetScin*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetScin,allocator<JPetScin> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetSigCh*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetSigCh,allocator<JPetSigCh> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetSignal*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetSignal,allocator<JPetSignal> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetTRB*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetTRB,allocator<JPetTRB> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(JPetTSlot*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetWriterDict_606_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetWriter*) G__getstructoffset())->Write(*(vector<JPetTSlot,allocator<JPetTSlot> >*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJPetWriterDict {
 public:
  G__Sizep2memfuncJPetWriterDict(): p(&G__Sizep2memfuncJPetWriterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJPetWriterDict::*p)();
};

size_t G__get_sizep2memfuncJPetWriterDict()
{
  G__Sizep2memfuncJPetWriterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJPetWriterDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJPetWriterDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__JPetWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<EdgeType,float>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType> >",117,G__get_linked_tagnum(&G__JPetWriterDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SingleCh>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > >",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ExtendedThreshold>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetSigCh>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetBarrelSlot>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetEvent>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetEventcOallocatorlEJPetEventgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetEventcOallocatorlEJPetEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetEventcOallocatorlEJPetEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetEventcOallocatorlEJPetEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetEventcOallocatorlEJPetEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetHit>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetHitcOallocatorlEJPetHitgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetHitcOallocatorlEJPetHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetHitcOallocatorlEJPetHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetHitcOallocatorlEJPetHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetHitcOallocatorlEJPetHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetPM>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetPMcOallocatorlEJPetPMgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetPMcOallocatorlEJPetPMgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetPMcOallocatorlEJPetPMgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetPMcOallocatorlEJPetPMgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetPMcOallocatorlEJPetPMgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetScin>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetScincOallocatorlEJPetScingRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetScincOallocatorlEJPetScingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetScincOallocatorlEJPetScingRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetScincOallocatorlEJPetScingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetScincOallocatorlEJPetScingRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetSignal>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetSignalcOallocatorlEJPetSignalgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSignalcOallocatorlEJPetSignalgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetSignalcOallocatorlEJPetSignalgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSignalcOallocatorlEJPetSignalgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetSignalcOallocatorlEJPetSignalgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetTRB>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetTRBcOallocatorlEJPetTRBgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTRBcOallocatorlEJPetTRBgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetTRBcOallocatorlEJPetTRBgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTRBcOallocatorlEJPetTRBgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetTRBcOallocatorlEJPetTRBgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetTSlot>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetWriterDictLN_vectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarJPetWriterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJPetWriter(void) {
   /* JPetWriter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JPetWriterDictLN_JPetWriter));
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_4, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetBarrelSlot' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_5, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetBarrelSlot,allocator<JPetBarrelSlot> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_6, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetEvent' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_7, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetEvent,allocator<JPetEvent> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_8, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetHit' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_9, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetHit,allocator<JPetHit> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_10, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetPM' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetPM,allocator<JPetPM> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_12, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetScin' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_13, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetScin,allocator<JPetScin> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_14, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetSigCh' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_15, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetSigCh,allocator<JPetSigCh> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_16, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetSignal' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_17, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetSignal,allocator<JPetSignal> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_18, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetTRB' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_19, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetTRB,allocator<JPetTRB> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_20, 103, -1, -1, 0, 1, 1, 1, 0, "u 'JPetTSlot' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__JPetWriterDict_606_0_21, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JPetTSlot,allocator<JPetTSlot> >' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJPetWriterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJPetWriterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJPetWriterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JPetWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__JPetWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetBarrelSlot = { "JPetBarrelSlot" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetScin = { "JPetScin" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetPM = { "JPetPM" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetTRB = { "JPetTRB" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetSigCh = { "JPetSigCh" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR = { "map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR = { "vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetSignal = { "JPetSignal" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR = { "vector<ExtendedThreshold,allocator<ExtendedThreshold> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ExtendedThreshold,allocator<ExtendedThreshold> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetTSlot = { "JPetTSlot" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR = { "vector<JPetSigCh,allocator<JPetSigCh> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetSigCh,allocator<JPetSigCh> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetHit = { "JPetHit" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetEvent = { "JPetEvent" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_JPetWriter = { "JPetWriter" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgR = { "vector<JPetBarrelSlot,allocator<JPetBarrelSlot> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetBarrelSlot,allocator<JPetBarrelSlot> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetEventcOallocatorlEJPetEventgRsPgR = { "vector<JPetEvent,allocator<JPetEvent> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetEventcOallocatorlEJPetEventgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetEvent,allocator<JPetEvent> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetHitcOallocatorlEJPetHitgRsPgR = { "vector<JPetHit,allocator<JPetHit> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetHitcOallocatorlEJPetHitgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetHit,allocator<JPetHit> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetPMcOallocatorlEJPetPMgRsPgR = { "vector<JPetPM,allocator<JPetPM> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetPMcOallocatorlEJPetPMgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetPM,allocator<JPetPM> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetScincOallocatorlEJPetScingRsPgR = { "vector<JPetScin,allocator<JPetScin> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetScincOallocatorlEJPetScingRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetScin,allocator<JPetScin> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetSignalcOallocatorlEJPetSignalgRsPgR = { "vector<JPetSignal,allocator<JPetSignal> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSignalcOallocatorlEJPetSignalgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetSignal,allocator<JPetSignal> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetTRBcOallocatorlEJPetTRBgRsPgR = { "vector<JPetTRB,allocator<JPetTRB> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTRBcOallocatorlEJPetTRBgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetTRB,allocator<JPetTRB> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_vectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgR = { "vector<JPetTSlot,allocator<JPetTSlot> >" , 99 , -1 };
G__linked_taginfo G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetTSlot,allocator<JPetTSlot> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJPetWriterDict() {
  G__JPetWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__JPetWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_JPetBarrelSlot.tagnum = -1 ;
  G__JPetWriterDictLN_JPetScin.tagnum = -1 ;
  G__JPetWriterDictLN_JPetPM.tagnum = -1 ;
  G__JPetWriterDictLN_JPetTRB.tagnum = -1 ;
  G__JPetWriterDictLN_JPetSigCh.tagnum = -1 ;
  G__JPetWriterDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_JPetSignal.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_JPetTSlot.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__JPetWriterDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__JPetWriterDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__JPetWriterDictLN_JPetHit.tagnum = -1 ;
  G__JPetWriterDictLN_JPetEvent.tagnum = -1 ;
  G__JPetWriterDictLN_JPetWriter.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetEventcOallocatorlEJPetEventgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetEventcOallocatorlEJPetEventgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetHitcOallocatorlEJPetHitgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetHitcOallocatorlEJPetHitgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetPMcOallocatorlEJPetPMgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetPMcOallocatorlEJPetPMgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetScincOallocatorlEJPetScingRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetScincOallocatorlEJPetScingRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetSignalcOallocatorlEJPetSignalgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSignalcOallocatorlEJPetSignalgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetTRBcOallocatorlEJPetTRBgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTRBcOallocatorlEJPetTRBgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetWriterDictLN_vectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgR.tagnum = -1 ;
  G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJPetWriterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetBarrelSlot);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetScin);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetPM);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetTRB);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetSigCh);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetSignal);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEExtendedThresholdcOallocatorlEExtendedThresholdgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetTSlot);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetHit);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_JPetWriter),sizeof(JPetWriter),-1,33792,(char*)NULL,NULL,G__setup_memfuncJPetWriter);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetBarrelSlotcOallocatorlEJPetBarrelSlotgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetEventcOallocatorlEJPetEventgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetEventcOallocatorlEJPetEventgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetHitcOallocatorlEJPetHitgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetHitcOallocatorlEJPetHitgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetPMcOallocatorlEJPetPMgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetPMcOallocatorlEJPetPMgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetScincOallocatorlEJPetScingRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetScincOallocatorlEJPetScingRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetSignalcOallocatorlEJPetSignalgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetSignalcOallocatorlEJPetSignalgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetTRBcOallocatorlEJPetTRBgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTRBcOallocatorlEJPetTRBgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_vectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetWriterDictLN_reverse_iteratorlEvectorlEJPetTSlotcOallocatorlEJPetTSlotgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupJPetWriterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJPetWriterDict()");
  G__set_cpp_environmentJPetWriterDict();
  G__cpp_setup_tagtableJPetWriterDict();

  G__cpp_setup_inheritanceJPetWriterDict();

  G__cpp_setup_typetableJPetWriterDict();

  G__cpp_setup_memvarJPetWriterDict();

  G__cpp_setup_memfuncJPetWriterDict();
  G__cpp_setup_globalJPetWriterDict();
  G__cpp_setup_funcJPetWriterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJPetWriterDict();
  return;
}
class G__cpp_setup_initJPetWriterDict {
  public:
    G__cpp_setup_initJPetWriterDict() { G__add_setup_func("JPetWriterDict",(G__incsetup)(&G__cpp_setupJPetWriterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJPetWriterDict() { G__remove_setup_func("JPetWriterDict"); }
};
G__cpp_setup_initJPetWriterDict G__cpp_setup_initializerJPetWriterDict;

