/********************************************************************
* JPetScinDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetScinDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetScinDict();
extern void G__cpp_setup_inheritanceJPetScinDict();
extern void G__cpp_setup_typetableJPetScinDict();
extern void G__cpp_setup_memvarJPetScinDict();
extern void G__cpp_setup_globalJPetScinDict();
extern void G__cpp_setup_memfuncJPetScinDict();
extern void G__cpp_setup_funcJPetScinDict();
extern void G__set_cpp_environmentJPetScinDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetScin.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetScinDictLN_TClass;
extern G__linked_taginfo G__JPetScinDictLN_TBuffer;
extern G__linked_taginfo G__JPetScinDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetScinDictLN_TObject;
extern G__linked_taginfo G__JPetScinDictLN_TNamed;
extern G__linked_taginfo G__JPetScinDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetScinDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetScinDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetScinDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetScinDictLN_JPetScin;
extern G__linked_taginfo G__JPetScinDictLN_JPetScincLcLDimension;
extern G__linked_taginfo G__JPetScinDictLN_JPetScincLcLScinDimensions;

/* STUB derived class for protected member access */
