/********************************************************************
* JPetBarrelSlotDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetBarrelSlotDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetBarrelSlotDict();
extern void G__cpp_setup_inheritanceJPetBarrelSlotDict();
extern void G__cpp_setup_typetableJPetBarrelSlotDict();
extern void G__cpp_setup_memvarJPetBarrelSlotDict();
extern void G__cpp_setup_globalJPetBarrelSlotDict();
extern void G__cpp_setup_memfuncJPetBarrelSlotDict();
extern void G__cpp_setup_funcJPetBarrelSlotDict();
extern void G__set_cpp_environmentJPetBarrelSlotDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetBarrelSlot.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetBarrelSlotDictLN_TClass;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_TBuffer;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_TObject;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_TNamed;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetBarrelSlotDictLN_JPetBarrelSlot;

/* STUB derived class for protected member access */
