/********************************************************************
* JPetPMDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetPMDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetPMDict();
extern void G__cpp_setup_inheritanceJPetPMDict();
extern void G__cpp_setup_typetableJPetPMDict();
extern void G__cpp_setup_memvarJPetPMDict();
extern void G__cpp_setup_globalJPetPMDict();
extern void G__cpp_setup_memfuncJPetPMDict();
extern void G__cpp_setup_funcJPetPMDict();
extern void G__set_cpp_environmentJPetPMDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetPM.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetPMDictLN_TClass;
extern G__linked_taginfo G__JPetPMDictLN_TBuffer;
extern G__linked_taginfo G__JPetPMDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetPMDictLN_TObject;
extern G__linked_taginfo G__JPetPMDictLN_TNamed;
extern G__linked_taginfo G__JPetPMDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetPMDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetPMDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetPMDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetPMDictLN_JPetPM;
extern G__linked_taginfo G__JPetPMDictLN_JPetPMcLcLSide;
extern G__linked_taginfo G__JPetPMDictLN_JPetPMcLcLGainNumber;
extern G__linked_taginfo G__JPetPMDictLN_pairlEfloatcOfloatgR;

/* STUB derived class for protected member access */
