/********************************************************************
* JPetUserDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetUserDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetUserDict();
extern void G__cpp_setup_inheritanceJPetUserDict();
extern void G__cpp_setup_typetableJPetUserDict();
extern void G__cpp_setup_memvarJPetUserDict();
extern void G__cpp_setup_globalJPetUserDict();
extern void G__cpp_setup_memfuncJPetUserDict();
extern void G__cpp_setup_funcJPetUserDict();
extern void G__set_cpp_environmentJPetUserDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetUser.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetUserDictLN_TClass;
extern G__linked_taginfo G__JPetUserDictLN_TBuffer;
extern G__linked_taginfo G__JPetUserDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetUserDictLN_TObject;
extern G__linked_taginfo G__JPetUserDictLN_TNamed;
extern G__linked_taginfo G__JPetUserDictLN_string;
extern G__linked_taginfo G__JPetUserDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetUserDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetUserDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetUserDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetUserDictLN_JPetUser;

/* STUB derived class for protected member access */
