/********************************************************************
* JPetManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetManagerDict();
extern void G__cpp_setup_inheritanceJPetManagerDict();
extern void G__cpp_setup_typetableJPetManagerDict();
extern void G__cpp_setup_memvarJPetManagerDict();
extern void G__cpp_setup_globalJPetManagerDict();
extern void G__cpp_setup_memfuncJPetManagerDict();
extern void G__cpp_setup_funcJPetManagerDict();
extern void G__set_cpp_environmentJPetManagerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetManagerDictLN_TClass;
extern G__linked_taginfo G__JPetManagerDictLN_TBuffer;
extern G__linked_taginfo G__JPetManagerDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetManagerDictLN_TObject;
extern G__linked_taginfo G__JPetManagerDictLN_TNamed;
extern G__linked_taginfo G__JPetManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetManagerDictLN_JPetAnalysisModule;
extern G__linked_taginfo G__JPetManagerDictLN_JPetCmdParser;
extern G__linked_taginfo G__JPetManagerDictLN_JPetParamManager;
extern G__linked_taginfo G__JPetManagerDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__JPetManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetManagerDictLN_JPetManager;
extern G__linked_taginfo G__JPetManagerDictLN_vectorlEJPetAnalysisModulemUcOallocatorlEJPetAnalysisModulemUgRsPgR;
extern G__linked_taginfo G__JPetManagerDictLN_reverse_iteratorlEvectorlEJPetAnalysisModulemUcOallocatorlEJPetAnalysisModulemUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
