//
// File generated by rootcint at Wed Mar 12 14:21:56 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JPetSigChDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JPetSigChDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JPetSigCh_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JPetSigCh(void *p = 0);
   static void *newArray_JPetSigCh(Long_t size, void *p);
   static void delete_JPetSigCh(void *p);
   static void deleteArray_JPetSigCh(void *p);
   static void destruct_JPetSigCh(void *p);
   static void streamer_JPetSigCh(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JPetSigCh*)
   {
      ::JPetSigCh *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JPetSigCh >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JPetSigCh", ::JPetSigCh::Class_Version(), "./JPetSigCh.h", 19,
                  typeid(::JPetSigCh), DefineBehavior(ptr, ptr),
                  &::JPetSigCh::Dictionary, isa_proxy, 0,
                  sizeof(::JPetSigCh) );
      instance.SetNew(&new_JPetSigCh);
      instance.SetNewArray(&newArray_JPetSigCh);
      instance.SetDelete(&delete_JPetSigCh);
      instance.SetDeleteArray(&deleteArray_JPetSigCh);
      instance.SetDestructor(&destruct_JPetSigCh);
      instance.SetStreamerFunc(&streamer_JPetSigCh);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JPetSigCh*)
   {
      return GenerateInitInstanceLocal((::JPetSigCh*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JPetSigCh*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *JPetSigCh::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *JPetSigCh::Class_Name()
{
   return "JPetSigCh";
}

//______________________________________________________________________________
const char *JPetSigCh::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JPetSigCh*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int JPetSigCh::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JPetSigCh*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void JPetSigCh::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JPetSigCh*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *JPetSigCh::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JPetSigCh*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void JPetSigCh::Streamer(TBuffer &R__b)
{
   // Stream an object of class JPetSigCh.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TNamed::Streamer(R__b);
      R__b >> fAmpl;
      {
         JPetSigCh::ChSet &R__stl =  fChannels;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >));
         if (R__tcl1==0) {
            Error("fChannels streamer","Missing the TClass object for map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b >> fIsSlow;
      fPM.Streamer(R__b);
      fTRB.Streamer(R__b);
      fScin.Streamer(R__b);
      fBarrelSlot.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, JPetSigCh::IsA());
   } else {
      R__c = R__b.WriteVersion(JPetSigCh::IsA(), kTRUE);
      TNamed::Streamer(R__b);
      R__b << fAmpl;
      {
         JPetSigCh::ChSet &R__stl =  fChannels;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >));
         if (R__tcl1==0) {
            Error("fChannels streamer","Missing the TClass object for map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >!");
            return;
         }
            JPetSigCh::ChSet::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b << fIsSlow;
      fPM.Streamer(R__b);
      fTRB.Streamer(R__b);
      fScin.Streamer(R__b);
      fBarrelSlot.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void JPetSigCh::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JPetSigCh.
      TClass *R__cl = ::JPetSigCh::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAmpl", &fAmpl);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fChannels", (void*)&fChannels);
      R__insp.InspectMember("JPetSigCh::ChSet", (void*)&fChannels, "fChannels.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIsSlow", &fIsSlow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPM", &fPM);
      R__insp.InspectMember(fPM, "fPM.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTRB", &fTRB);
      R__insp.InspectMember(fTRB, "fTRB.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fScin", &fScin);
      R__insp.InspectMember(fScin, "fScin.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBarrelSlot", &fBarrelSlot);
      R__insp.InspectMember(fBarrelSlot, "fBarrelSlot.");
      TNamed::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_JPetSigCh(void *p) {
      return  p ? new(p) ::JPetSigCh : new ::JPetSigCh;
   }
   static void *newArray_JPetSigCh(Long_t nElements, void *p) {
      return p ? new(p) ::JPetSigCh[nElements] : new ::JPetSigCh[nElements];
   }
   // Wrapper around operator delete
   static void delete_JPetSigCh(void *p) {
      delete ((::JPetSigCh*)p);
   }
   static void deleteArray_JPetSigCh(void *p) {
      delete [] ((::JPetSigCh*)p);
   }
   static void destruct_JPetSigCh(void *p) {
      typedef ::JPetSigCh current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_JPetSigCh(TBuffer &buf, void *obj) {
      ((::JPetSigCh*)obj)->::JPetSigCh::Streamer(buf);
   }
} // end of namespace ROOT for class ::JPetSigCh

namespace ROOT {
   void maplEJPetSigChcLcLEdgeTypecOfloatgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEJPetSigChcLcLEdgeTypecOfloatgR_Dictionary();
   static void *new_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p = 0);
   static void *newArray_maplEJPetSigChcLcLEdgeTypecOfloatgR(Long_t size, void *p);
   static void delete_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p);
   static void deleteArray_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p);
   static void destruct_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<JPetSigCh::EdgeType,float>*)
   {
      map<JPetSigCh::EdgeType,float> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<JPetSigCh::EdgeType,float>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<JPetSigCh::EdgeType,float>", -2, "prec_stl/map", 63,
                  typeid(map<JPetSigCh::EdgeType,float>), DefineBehavior(ptr, ptr),
                  0, &maplEJPetSigChcLcLEdgeTypecOfloatgR_Dictionary, isa_proxy, 0,
                  sizeof(map<JPetSigCh::EdgeType,float>) );
      instance.SetNew(&new_maplEJPetSigChcLcLEdgeTypecOfloatgR);
      instance.SetNewArray(&newArray_maplEJPetSigChcLcLEdgeTypecOfloatgR);
      instance.SetDelete(&delete_maplEJPetSigChcLcLEdgeTypecOfloatgR);
      instance.SetDeleteArray(&deleteArray_maplEJPetSigChcLcLEdgeTypecOfloatgR);
      instance.SetDestructor(&destruct_maplEJPetSigChcLcLEdgeTypecOfloatgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<JPetSigCh::EdgeType,float> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<JPetSigCh::EdgeType,float>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEJPetSigChcLcLEdgeTypecOfloatgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<JPetSigCh::EdgeType,float>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<JPetSigCh::EdgeType,float> : new map<JPetSigCh::EdgeType,float>;
   }
   static void *newArray_maplEJPetSigChcLcLEdgeTypecOfloatgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<JPetSigCh::EdgeType,float>[nElements] : new map<JPetSigCh::EdgeType,float>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p) {
      delete ((map<JPetSigCh::EdgeType,float>*)p);
   }
   static void deleteArray_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p) {
      delete [] ((map<JPetSigCh::EdgeType,float>*)p);
   }
   static void destruct_maplEJPetSigChcLcLEdgeTypecOfloatgR(void *p) {
      typedef map<JPetSigCh::EdgeType,float> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<JPetSigCh::EdgeType,float>

namespace ROOT {
   void vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR_Dictionary();
   static void *new_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p = 0);
   static void *newArray_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(Long_t size, void *p);
   static void delete_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p);
   static void deleteArray_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p);
   static void destruct_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<map<JPetSigCh::EdgeType,float> >*)
   {
      vector<map<JPetSigCh::EdgeType,float> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<map<JPetSigCh::EdgeType,float> >),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<map<JPetSigCh::EdgeType,float> >", -2, "prec_stl/vector", 49,
                  typeid(vector<map<JPetSigCh::EdgeType,float> >), DefineBehavior(ptr, ptr),
                  0, &vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<map<JPetSigCh::EdgeType,float> >) );
      instance.SetNew(&new_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR);
      instance.SetNewArray(&newArray_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR);
      instance.SetDelete(&delete_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR);
      instance.SetDestructor(&destruct_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<map<JPetSigCh::EdgeType,float> > >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<map<JPetSigCh::EdgeType,float> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<map<JPetSigCh::EdgeType,float> >*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<map<JPetSigCh::EdgeType,float> > : new vector<map<JPetSigCh::EdgeType,float> >;
   }
   static void *newArray_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<map<JPetSigCh::EdgeType,float> >[nElements] : new vector<map<JPetSigCh::EdgeType,float> >[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p) {
      delete ((vector<map<JPetSigCh::EdgeType,float> >*)p);
   }
   static void deleteArray_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p) {
      delete [] ((vector<map<JPetSigCh::EdgeType,float> >*)p);
   }
   static void destruct_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatgRsPgR(void *p) {
      typedef vector<map<JPetSigCh::EdgeType,float> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<map<JPetSigCh::EdgeType,float> >

/********************************************************
* JPetSigChDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJPetSigChDict();

extern "C" void G__set_cpp_environmentJPetSigChDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JPetSigCh.h");
  G__cpp_reset_tagtableJPetSigChDict();
}
#include <new>
extern "C" int G__cpp_dllrevJPetSigChDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JPetSigCh */
static int G__JPetSigChDict_464_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetSigCh* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetSigCh[n];
     } else {
       p = new((void*) gvp) JPetSigCh[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetSigCh;
     } else {
       p = new((void*) gvp) JPetSigCh;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetSigCh* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new JPetSigCh(*(JPetSigCh*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) JPetSigCh(*(JPetSigCh*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetSigCh& obj = ((JPetSigCh*) G__getstructoffset())->operator=(*((const JPetSigCh*) G__int(libp->para[0])));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetSigCh* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetSigCh((float) G__double(libp->para[0]), (float) G__double(libp->para[1]));
     } else {
       p = new((void*) gvp) JPetSigCh((float) G__double(libp->para[0]), (float) G__double(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetSigCh((float) G__double(libp->para[0]));
     } else {
       p = new((void*) gvp) JPetSigCh((float) G__double(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const JPetSigCh*) G__getstructoffset())->isSlow());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const JPetSigCh*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const JPetSigCh*) G__getstructoffset())->getAmpl());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 102, (double) ((const JPetSigCh*) G__getstructoffset())->getTime((JPetSigCh::EdgeType) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 102, (double) ((const JPetSigCh*) G__getstructoffset())->getTime((JPetSigCh::EdgeType) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 102, (double) ((const JPetSigCh*) G__getstructoffset())->getTime());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetPM* pobj;
         const JPetPM xobj = ((const JPetSigCh*) G__getstructoffset())->getPM();
         pobj = new JPetPM(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetTRB* pobj;
         const JPetTRB xobj = ((const JPetSigCh*) G__getstructoffset())->getTRB();
         pobj = new JPetTRB(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetScin* pobj;
         const JPetScin xobj = ((const JPetSigCh*) G__getstructoffset())->getScin();
         pobj = new JPetScin(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetBarrelSlot* pobj;
         const JPetBarrelSlot xobj = ((const JPetSigCh*) G__getstructoffset())->getBarrelSlot();
         pobj = new JPetBarrelSlot(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetSigCh::ChSet* pobj;
         const JPetSigCh::ChSet xobj = ((const JPetSigCh*) G__getstructoffset())->getChSet();
         pobj = new JPetSigCh::ChSet(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetSigCh*) G__getstructoffset())->addCh((float) G__double(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetSigCh*) G__getstructoffset())->setPM(*(JPetPM*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetSigCh*) G__getstructoffset())->setTRB(*(JPetTRB*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetSigCh*) G__getstructoffset())->setScin(*(JPetScin*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetSigCh*) G__getstructoffset())->setBarrelSlot(*(JPetBarrelSlot*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JPetSigCh::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetSigCh::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JPetSigCh::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JPetSigCh::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetSigCh*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetSigCh::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JPetSigCh::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetSigCh::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetSigChDict_464_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JPetSigCh::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JPetSigCh G__TJPetSigCh;
static int G__JPetSigChDict_464_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JPetSigCh*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JPetSigCh*) (soff+(sizeof(JPetSigCh)*i)))->~G__TJPetSigCh();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JPetSigCh*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JPetSigCh*) (soff))->~G__TJPetSigCh();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JPetSigCh */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJPetSigChDict {
 public:
  G__Sizep2memfuncJPetSigChDict(): p(&G__Sizep2memfuncJPetSigChDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJPetSigChDict::*p)();
};

size_t G__get_sizep2memfuncJPetSigChDict()
{
  G__Sizep2memfuncJPetSigChDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJPetSigChDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh))) {
     JPetSigCh *G__Lderived;
     G__Lderived=(JPetSigCh*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh),G__get_linked_tagnum(&G__JPetSigChDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh),G__get_linked_tagnum(&G__JPetSigChDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJPetSigChDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<EdgeType,float>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType> >",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SingleCh",117,G__get_linked_tagnum(&G__JPetSigChDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SingleCh>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetSigChDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > >",117,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ChSet",117,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JPetSigCh */
static void G__setup_memvarJPetSigCh(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh));
   { JPetSigCh *p; p=(JPetSigCh*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigChcLcLEdgeType),-1,-2,1,G__FastAllocString(2048).Format("kRising=%lldLL",(long long)JPetSigCh::kRising).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigChcLcLEdgeType),-1,-2,1,G__FastAllocString(2048).Format("kFalling=%lldLL",(long long)JPetSigCh::kFalling).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetSigChDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"fAmpl=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),G__defined_typename("ChSet"),-1,2,"fChannels=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fIsSlow=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetPM),-1,-1,2,"fPM=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetTRB),-1,-1,2,"fTRB=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetScin),-1,-1,2,"fScin=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetSigChDictLN_JPetBarrelSlot),-1,-1,2,"fBarrelSlot=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJPetSigChDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJPetSigCh(void) {
   /* JPetSigCh */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh));
   G__memfunc_setup("JPetSigCh",833,G__JPetSigChDict_464_0_1, 105, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JPetSigCh",833,G__JPetSigChDict_464_0_2, 105, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh), -1, 0, 1, 1, 1, 0, "u 'JPetSigCh' - 11 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__JPetSigChDict_464_0_3, 117, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh), -1, 1, 1, 1, 1, 0, "u 'JPetSigCh' - 10 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JPetSigCh",833,G__JPetSigChDict_464_0_4, 105, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetSigCh), -1, 0, 2, 1, 1, 0, 
"f - - 0 - EdgeTime f - - 0 '0' FallEdgeTime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isSlow",641,G__JPetSigChDict_464_0_5, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__JPetSigChDict_464_0_6, 107, -1, G__defined_typename("size_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getAmpl",714,G__JPetSigChDict_464_0_7, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTime",719,G__JPetSigChDict_464_0_8, 102, -1, -1, 0, 2, 1, 1, 8, 
"i 'JPetSigCh::EdgeType' - 0 'kRising' type i - - 0 '0' ch_no", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getPM",477,G__JPetSigChDict_464_0_9, 117, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetPM), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTRB",552,G__JPetSigChDict_464_0_10, 117, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetTRB), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getScin",717,G__JPetSigChDict_464_0_11, 117, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetScin), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBarrelSlot",1338,G__JPetSigChDict_464_0_12, 117, G__get_linked_tagnum(&G__JPetSigChDictLN_JPetBarrelSlot), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getChSet",791,G__JPetSigChDict_464_0_13, 117, G__get_linked_tagnum(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR), G__defined_typename("JPetSigCh::ChSet"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addCh",468,G__JPetSigChDict_464_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"f - - 0 - edge_time f - - 0 - fall_edge_time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setPM",489,G__JPetSigChDict_464_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'JPetPM' - 11 - pm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTRB",564,G__JPetSigChDict_464_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'JPetTRB' - 11 - trb", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setScin",729,G__JPetSigChDict_464_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'JPetScin' - 11 - scin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setBarrelSlot",1350,G__JPetSigChDict_464_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'JPetBarrelSlot' - 11 - barrel_slot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__JPetSigChDict_464_0_19, 85, G__get_linked_tagnum(&G__JPetSigChDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JPetSigCh::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__JPetSigChDict_464_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetSigCh::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__JPetSigChDict_464_0_21, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JPetSigCh::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__JPetSigChDict_464_0_22, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JPetSigCh::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__JPetSigChDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__JPetSigChDict_464_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__JPetSigChDict_464_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetSigCh::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__JPetSigChDict_464_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JPetSigCh::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__JPetSigChDict_464_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetSigCh::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__JPetSigChDict_464_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JPetSigCh::DeclFileLine) ), 0);
   G__memfunc_setup("init",436,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JPetSigCh", 959, G__JPetSigChDict_464_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJPetSigChDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJPetSigChDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJPetSigChDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JPetSigChDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__JPetSigChDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_JPetPM = { "JPetPM" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_JPetBarrelSlot = { "JPetBarrelSlot" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_JPetScin = { "JPetScin" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_JPetTRB = { "JPetTRB" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_JPetSigCh = { "JPetSigCh" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_JPetSigChcLcLEdgeType = { "JPetSigCh::EdgeType" , 101 , -1 };
G__linked_taginfo G__JPetSigChDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR = { "map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR = { "vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >" , 99 , -1 };
G__linked_taginfo G__JPetSigChDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJPetSigChDict() {
  G__JPetSigChDictLN_TClass.tagnum = -1 ;
  G__JPetSigChDictLN_TBuffer.tagnum = -1 ;
  G__JPetSigChDictLN_TMemberInspector.tagnum = -1 ;
  G__JPetSigChDictLN_TObject.tagnum = -1 ;
  G__JPetSigChDictLN_TNamed.tagnum = -1 ;
  G__JPetSigChDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JPetSigChDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetSigChDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JPetSigChDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__JPetSigChDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__JPetSigChDictLN_JPetPM.tagnum = -1 ;
  G__JPetSigChDictLN_JPetBarrelSlot.tagnum = -1 ;
  G__JPetSigChDictLN_JPetScin.tagnum = -1 ;
  G__JPetSigChDictLN_JPetTRB.tagnum = -1 ;
  G__JPetSigChDictLN_JPetSigCh.tagnum = -1 ;
  G__JPetSigChDictLN_JPetSigChcLcLEdgeType.tagnum = -1 ;
  G__JPetSigChDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR.tagnum = -1 ;
  G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__JPetSigChDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJPetSigChDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_JPetPM);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_JPetBarrelSlot);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_JPetScin);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_JPetTRB);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_JPetSigCh),sizeof(JPetSigCh),-1,64256,(char*)NULL,G__setup_memvarJPetSigCh,G__setup_memfuncJPetSigCh);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_JPetSigChcLcLEdgeType);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetSigChDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupJPetSigChDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJPetSigChDict()");
  G__set_cpp_environmentJPetSigChDict();
  G__cpp_setup_tagtableJPetSigChDict();

  G__cpp_setup_inheritanceJPetSigChDict();

  G__cpp_setup_typetableJPetSigChDict();

  G__cpp_setup_memvarJPetSigChDict();

  G__cpp_setup_memfuncJPetSigChDict();
  G__cpp_setup_globalJPetSigChDict();
  G__cpp_setup_funcJPetSigChDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJPetSigChDict();
  return;
}
class G__cpp_setup_initJPetSigChDict {
  public:
    G__cpp_setup_initJPetSigChDict() { G__add_setup_func("JPetSigChDict",(G__incsetup)(&G__cpp_setupJPetSigChDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJPetSigChDict() { G__remove_setup_func("JPetSigChDict"); }
};
G__cpp_setup_initJPetSigChDict G__cpp_setup_initializerJPetSigChDict;

