/********************************************************************
* JPetHLDReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetHLDReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetHLDReaderDict();
extern void G__cpp_setup_inheritanceJPetHLDReaderDict();
extern void G__cpp_setup_typetableJPetHLDReaderDict();
extern void G__cpp_setup_memvarJPetHLDReaderDict();
extern void G__cpp_setup_globalJPetHLDReaderDict();
extern void G__cpp_setup_memfuncJPetHLDReaderDict();
extern void G__cpp_setup_funcJPetHLDReaderDict();
extern void G__set_cpp_environmentJPetHLDReaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetHLDReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetHLDReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetHLDReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JPetHLDReaderDictLN_TTree;
extern G__linked_taginfo G__JPetHLDReaderDictLN_TFile;
extern G__linked_taginfo G__JPetHLDReaderDictLN_TBranch;
extern G__linked_taginfo G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__JPetHLDReaderDictLN_TSlot;
extern G__linked_taginfo G__JPetHLDReaderDictLN_JPetHLDReader;

/* STUB derived class for protected member access */
