//
// File generated by rootcint at Tue Mar 11 21:21:40 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JPetHLDReaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JPetHLDReaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JPetHLDReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void JPetHLDReader_Dictionary();
   static void *new_JPetHLDReader(void *p = 0);
   static void *newArray_JPetHLDReader(Long_t size, void *p);
   static void delete_JPetHLDReader(void *p);
   static void deleteArray_JPetHLDReader(void *p);
   static void destruct_JPetHLDReader(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JPetHLDReader*)
   {
      ::JPetHLDReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::JPetHLDReader),0);
      static ::ROOT::TGenericClassInfo 
         instance("JPetHLDReader", "./JPetHLDReader.h", 20,
                  typeid(::JPetHLDReader), DefineBehavior(ptr, ptr),
                  0, &JPetHLDReader_Dictionary, isa_proxy, 0,
                  sizeof(::JPetHLDReader) );
      instance.SetNew(&new_JPetHLDReader);
      instance.SetNewArray(&newArray_JPetHLDReader);
      instance.SetDelete(&delete_JPetHLDReader);
      instance.SetDeleteArray(&deleteArray_JPetHLDReader);
      instance.SetDestructor(&destruct_JPetHLDReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JPetHLDReader*)
   {
      return GenerateInitInstanceLocal((::JPetHLDReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JPetHLDReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void JPetHLDReader_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::JPetHLDReader*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_JPetHLDReader(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JPetHLDReader : new ::JPetHLDReader;
   }
   static void *newArray_JPetHLDReader(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JPetHLDReader[nElements] : new ::JPetHLDReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_JPetHLDReader(void *p) {
      delete ((::JPetHLDReader*)p);
   }
   static void deleteArray_JPetHLDReader(void *p) {
      delete [] ((::JPetHLDReader*)p);
   }
   static void destruct_JPetHLDReader(void *p) {
      typedef ::JPetHLDReader current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::JPetHLDReader

/********************************************************
* JPetHLDReaderDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJPetHLDReaderDict();

extern "C" void G__set_cpp_environmentJPetHLDReaderDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JPetHLDReader.h");
  G__cpp_reset_tagtableJPetHLDReaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevJPetHLDReaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JPetHLDReader */
static int G__JPetHLDReaderDict_519_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetHLDReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetHLDReader[n];
     } else {
       p = new((void*) gvp) JPetHLDReader[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetHLDReader;
     } else {
       p = new((void*) gvp) JPetHLDReader;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_JPetHLDReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetHLDReaderDict_519_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetHLDReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new JPetHLDReader((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) JPetHLDReader((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_JPetHLDReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetHLDReaderDict_519_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetHLDReader*) G__getstructoffset())->CloseFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetHLDReaderDict_519_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((const JPetHLDReader*) G__getstructoffset())->GetEntries());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetHLDReaderDict_519_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((JPetHLDReader*) G__getstructoffset())->GetEntry((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetHLDReaderDict_519_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JPetHLDReader*) G__getstructoffset())->OpenFile((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetHLDReaderDict_519_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetHLDReader*) G__getstructoffset())->ReadData();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetHLDReaderDict_519_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TSlot& obj = ((JPetHLDReader*) G__getstructoffset())->GetData();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JPetHLDReader G__TJPetHLDReader;
static int G__JPetHLDReaderDict_519_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JPetHLDReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JPetHLDReader*) (soff+(sizeof(JPetHLDReader)*i)))->~G__TJPetHLDReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JPetHLDReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JPetHLDReader*) (soff))->~G__TJPetHLDReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JPetHLDReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJPetHLDReaderDict {
 public:
  G__Sizep2memfuncJPetHLDReaderDict(): p(&G__Sizep2memfuncJPetHLDReaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJPetHLDReaderDict::*p)();
};

size_t G__get_sizep2memfuncJPetHLDReaderDict()
{
  G__Sizep2memfuncJPetHLDReaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJPetHLDReaderDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJPetHLDReaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JPetHLDReader */
static void G__setup_memvarJPetHLDReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JPetHLDReaderDictLN_JPetHLDReader));
   { JPetHLDReader *p; p=(JPetHLDReader*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_TBranch),-1,-1,2,"fBranch=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_TTree),-1,-1,2,"fTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_TSlot),-1,-1,2,"fTSlot=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetHLDReaderDictLN_TFile),-1,-1,2,"fFile=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJPetHLDReaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJPetHLDReader(void) {
   /* JPetHLDReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JPetHLDReaderDictLN_JPetHLDReader));
   G__memfunc_setup("JPetHLDReader",1182,G__JPetHLDReaderDict_519_0_1, 105, G__get_linked_tagnum(&G__JPetHLDReaderDictLN_JPetHLDReader), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JPetHLDReader",1182,G__JPetHLDReaderDict_519_0_2, 105, G__get_linked_tagnum(&G__JPetHLDReaderDictLN_JPetHLDReader), -1, 0, 1, 5, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseFile",886,G__JPetHLDReaderDict_519_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEntries",1018,G__JPetHLDReaderDict_519_0_4, 110, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEntry",818,G__JPetHLDReaderDict_519_0_5, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - entryNo", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OpenFile",786,G__JPetHLDReaderDict_519_0_6, 103, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadData",758,G__JPetHLDReaderDict_519_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetData",666,G__JPetHLDReaderDict_519_0_8, 117, G__get_linked_tagnum(&G__JPetHLDReaderDictLN_TSlot), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JPetHLDReader",1182,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__JPetHLDReaderDictLN_JPetHLDReader), -1, 0, 1, 1, 4, 0, "u 'JPetHLDReader' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "u 'JPetHLDReader' - 10 - -", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JPetHLDReader", 1308, G__JPetHLDReaderDict_519_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJPetHLDReaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJPetHLDReaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJPetHLDReaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JPetHLDReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_TSlot = { "TSlot" , 99 , -1 };
G__linked_taginfo G__JPetHLDReaderDictLN_JPetHLDReader = { "JPetHLDReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJPetHLDReaderDict() {
  G__JPetHLDReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetHLDReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__JPetHLDReaderDictLN_TTree.tagnum = -1 ;
  G__JPetHLDReaderDictLN_TFile.tagnum = -1 ;
  G__JPetHLDReaderDictLN_TBranch.tagnum = -1 ;
  G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__JPetHLDReaderDictLN_TSlot.tagnum = -1 ;
  G__JPetHLDReaderDictLN_JPetHLDReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJPetHLDReaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_TSlot);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JPetHLDReaderDictLN_JPetHLDReader),sizeof(JPetHLDReader),-1,36608,(char*)NULL,G__setup_memvarJPetHLDReader,G__setup_memfuncJPetHLDReader);
}
extern "C" void G__cpp_setupJPetHLDReaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJPetHLDReaderDict()");
  G__set_cpp_environmentJPetHLDReaderDict();
  G__cpp_setup_tagtableJPetHLDReaderDict();

  G__cpp_setup_inheritanceJPetHLDReaderDict();

  G__cpp_setup_typetableJPetHLDReaderDict();

  G__cpp_setup_memvarJPetHLDReaderDict();

  G__cpp_setup_memfuncJPetHLDReaderDict();
  G__cpp_setup_globalJPetHLDReaderDict();
  G__cpp_setup_funcJPetHLDReaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJPetHLDReaderDict();
  return;
}
class G__cpp_setup_initJPetHLDReaderDict {
  public:
    G__cpp_setup_initJPetHLDReaderDict() { G__add_setup_func("JPetHLDReaderDict",(G__incsetup)(&G__cpp_setupJPetHLDReaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJPetHLDReaderDict() { G__remove_setup_func("JPetHLDReaderDict"); }
};
G__cpp_setup_initJPetHLDReaderDict G__cpp_setup_initializerJPetHLDReaderDict;

