/********************************************************************
* mydict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mydict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemydict();
extern void G__cpp_setup_inheritancemydict();
extern void G__cpp_setup_typetablemydict();
extern void G__cpp_setup_memvarmydict();
extern void G__cpp_setup_globalmydict();
extern void G__cpp_setup_memfuncmydict();
extern void G__cpp_setup_funcmydict();
extern void G__set_cpp_environmentmydict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Unpacker2.h"
#include "Event.h"
#include "UnpackingModule.h"
#include "Unpacker_HPTDC_HR.h"
#include "Unpacker_HPTDC_VHR.h"
#include "TDCHit.h"
#include "ADCHit.h"
#include "Unpacker_HUB2.h"
#include "Unpacker_TRB2.h"
#include "Unpacker_Shower.h"
#include "Unpacker_Ecal_ADC.h"
#include "Unpacker_TRB3.h"
#include "Unpacker_Lattice_TDC.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mydictLN_TClass;
extern G__linked_taginfo G__mydictLN_TBuffer;
extern G__linked_taginfo G__mydictLN_TMemberInspector;
extern G__linked_taginfo G__mydictLN_TObject;
extern G__linked_taginfo G__mydictLN_string;
extern G__linked_taginfo G__mydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mydictLN_TClonesArray;
extern G__linked_taginfo G__mydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__mydictLN_TDCHit;
extern G__linked_taginfo G__mydictLN_ADCHit;
extern G__linked_taginfo G__mydictLN_Event;
extern G__linked_taginfo G__mydictLN_UnpackingModule;
extern G__linked_taginfo G__mydictLN_maplEstringcOUnpackingModulemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOUnpackingModulemUgRsPgRsPgR;
extern G__linked_taginfo G__mydictLN_maplEstringcOUnpackingModulemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOUnpackingModulemUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__mydictLN_Unpacker2;
extern G__linked_taginfo G__mydictLN_Unpacker2cLcLEventHdr;
extern G__linked_taginfo G__mydictLN_Unpacker2cLcLSubEventHdr;
extern G__linked_taginfo G__mydictLN_Unpacker_HPTDC_HR;
extern G__linked_taginfo G__mydictLN_InlCorrector;
extern G__linked_taginfo G__mydictLN_Unpacker_HPTDC_VHR;
extern G__linked_taginfo G__mydictLN_Unpacker_HUB2;
extern G__linked_taginfo G__mydictLN_Unpacker_TRB2;
extern G__linked_taginfo G__mydictLN_Unpacker_Shower;
extern G__linked_taginfo G__mydictLN_Unpacker_Ecal_ADC;
extern G__linked_taginfo G__mydictLN_Unpacker_TRB3;
extern G__linked_taginfo G__mydictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mydictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mydictLN_TH1F;
extern G__linked_taginfo G__mydictLN_Unpacker_Lattice_TDC;

/* STUB derived class for protected member access */
