/********************************************************************
* JPetTRBDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetTRBDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetTRBDict();
extern void G__cpp_setup_inheritanceJPetTRBDict();
extern void G__cpp_setup_typetableJPetTRBDict();
extern void G__cpp_setup_memvarJPetTRBDict();
extern void G__cpp_setup_globalJPetTRBDict();
extern void G__cpp_setup_memfuncJPetTRBDict();
extern void G__cpp_setup_funcJPetTRBDict();
extern void G__set_cpp_environmentJPetTRBDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetTRB.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetTRBDictLN_TClass;
extern G__linked_taginfo G__JPetTRBDictLN_TBuffer;
extern G__linked_taginfo G__JPetTRBDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetTRBDictLN_TObject;
extern G__linked_taginfo G__JPetTRBDictLN_TNamed;
extern G__linked_taginfo G__JPetTRBDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetTRBDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetTRBDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetTRBDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetTRBDictLN_JPetTRB;

/* STUB derived class for protected member access */
