if(NOT TINYXML_FOUND)
  find_path(TINYXML_INCLUDE_DIR tinyxml2.h)
  find_library(TINYXML_LIBRARY tinyxml2)
  mark_as_advanced(TINYXML_INCLUDE_DIR TINYXML_LIBRARY)

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(TINYXML DEFAULT_MSG
    TINYXML_LIBRARY TINYXML_INCLUDE_DIR)

  set(TINYXML_INCLUDE_DIRS ${TINYXML_INCLUDE_DIR})
  set(TINYXML_LIBRARIES ${TINYXML_LIBRARY})
endif(NOT TINYXML_FOUND)
