//
// File generated by rootcint at Wed Mar 12 14:22:03 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JPetTSlotDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JPetTSlotDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JPetTSlot_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JPetTSlot(void *p = 0);
   static void *newArray_JPetTSlot(Long_t size, void *p);
   static void delete_JPetTSlot(void *p);
   static void deleteArray_JPetTSlot(void *p);
   static void destruct_JPetTSlot(void *p);
   static void streamer_JPetTSlot(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JPetTSlot*)
   {
      ::JPetTSlot *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JPetTSlot >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JPetTSlot", ::JPetTSlot::Class_Version(), "./JPetTSlot.h", 11,
                  typeid(::JPetTSlot), DefineBehavior(ptr, ptr),
                  &::JPetTSlot::Dictionary, isa_proxy, 0,
                  sizeof(::JPetTSlot) );
      instance.SetNew(&new_JPetTSlot);
      instance.SetNewArray(&newArray_JPetTSlot);
      instance.SetDelete(&delete_JPetTSlot);
      instance.SetDeleteArray(&deleteArray_JPetTSlot);
      instance.SetDestructor(&destruct_JPetTSlot);
      instance.SetStreamerFunc(&streamer_JPetTSlot);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JPetTSlot*)
   {
      return GenerateInitInstanceLocal((::JPetTSlot*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JPetTSlot*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *JPetTSlot::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *JPetTSlot::Class_Name()
{
   return "JPetTSlot";
}

//______________________________________________________________________________
const char *JPetTSlot::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JPetTSlot*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int JPetTSlot::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JPetTSlot*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void JPetTSlot::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JPetTSlot*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *JPetTSlot::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JPetTSlot*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void JPetTSlot::Streamer(TBuffer &R__b)
{
   // Stream an object of class JPetTSlot.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TNamed::Streamer(R__b);
      {
         vector<JPetSigCh> &R__stl =  fSigChannels;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            JPetSigCh R__t;
            R__t.Streamer(R__b);
            R__stl.push_back(R__t);
         }
      }
      R__b.CheckByteCount(R__s, R__c, JPetTSlot::IsA());
   } else {
      R__c = R__b.WriteVersion(JPetTSlot::IsA(), kTRUE);
      TNamed::Streamer(R__b);
      {
         vector<JPetSigCh> &R__stl =  fSigChannels;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<JPetSigCh>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            ((JPetSigCh&)(*R__k)).Streamer(R__b);
            }
         }
      }
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void JPetTSlot::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JPetTSlot.
      TClass *R__cl = ::JPetTSlot::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSigChannels", (void*)&fSigChannels);
      R__insp.InspectMember("vector<JPetSigCh>", (void*)&fSigChannels, "fSigChannels.", false);
      TNamed::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_JPetTSlot(void *p) {
      return  p ? new(p) ::JPetTSlot : new ::JPetTSlot;
   }
   static void *newArray_JPetTSlot(Long_t nElements, void *p) {
      return p ? new(p) ::JPetTSlot[nElements] : new ::JPetTSlot[nElements];
   }
   // Wrapper around operator delete
   static void delete_JPetTSlot(void *p) {
      delete ((::JPetTSlot*)p);
   }
   static void deleteArray_JPetTSlot(void *p) {
      delete [] ((::JPetTSlot*)p);
   }
   static void destruct_JPetTSlot(void *p) {
      typedef ::JPetTSlot current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_JPetTSlot(TBuffer &buf, void *obj) {
      ((::JPetTSlot*)obj)->::JPetTSlot::Streamer(buf);
   }
} // end of namespace ROOT for class ::JPetTSlot

namespace ROOT {
   void vectorlEJPetSigChgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEJPetSigChgR_Dictionary();
   static void *new_vectorlEJPetSigChgR(void *p = 0);
   static void *newArray_vectorlEJPetSigChgR(Long_t size, void *p);
   static void delete_vectorlEJPetSigChgR(void *p);
   static void deleteArray_vectorlEJPetSigChgR(void *p);
   static void destruct_vectorlEJPetSigChgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<JPetSigCh>*)
   {
      vector<JPetSigCh> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<JPetSigCh>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<JPetSigCh>", -2, "prec_stl/vector", 49,
                  typeid(vector<JPetSigCh>), DefineBehavior(ptr, ptr),
                  0, &vectorlEJPetSigChgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<JPetSigCh>) );
      instance.SetNew(&new_vectorlEJPetSigChgR);
      instance.SetNewArray(&newArray_vectorlEJPetSigChgR);
      instance.SetDelete(&delete_vectorlEJPetSigChgR);
      instance.SetDeleteArray(&deleteArray_vectorlEJPetSigChgR);
      instance.SetDestructor(&destruct_vectorlEJPetSigChgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<JPetSigCh> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<JPetSigCh>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEJPetSigChgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<JPetSigCh>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEJPetSigChgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<JPetSigCh> : new vector<JPetSigCh>;
   }
   static void *newArray_vectorlEJPetSigChgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<JPetSigCh>[nElements] : new vector<JPetSigCh>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEJPetSigChgR(void *p) {
      delete ((vector<JPetSigCh>*)p);
   }
   static void deleteArray_vectorlEJPetSigChgR(void *p) {
      delete [] ((vector<JPetSigCh>*)p);
   }
   static void destruct_vectorlEJPetSigChgR(void *p) {
      typedef vector<JPetSigCh> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<JPetSigCh>

/********************************************************
* JPetTSlotDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJPetTSlotDict();

extern "C" void G__set_cpp_environmentJPetTSlotDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JPetTSlot.h");
  G__cpp_reset_tagtableJPetTSlotDict();
}
#include <new>
extern "C" int G__cpp_dllrevJPetTSlotDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JPetTSlot */
static int G__JPetTSlotDict_479_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetTSlot* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetTSlot[n];
     } else {
       p = new((void*) gvp) JPetTSlot[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JPetTSlot;
     } else {
       p = new((void*) gvp) JPetTSlot;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetTSlot* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new JPetTSlot(*(vector<JPetSigCh>*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) JPetTSlot(*(vector<JPetSigCh>*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetTSlot*) G__getstructoffset())->addCh(*(JPetSigCh*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const JPetTSlot*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const JPetTSlot*) G__getstructoffset())->getNumberOfSigCh());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<JPetSigCh>& obj = ((const JPetTSlot*) G__getstructoffset())->getSigChVect();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const JPetSigCh& obj = ((const JPetTSlot*) G__getstructoffset())->operator[]((int) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JPetTSlot::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetTSlot::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JPetTSlot::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JPetTSlot::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JPetTSlot*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetTSlot::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JPetTSlot::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JPetTSlot::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JPetTSlotDict_479_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JPetTSlot::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__JPetTSlotDict_479_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JPetTSlot* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JPetTSlot(*(JPetTSlot*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JPetTSlot G__TJPetTSlot;
static int G__JPetTSlotDict_479_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JPetTSlot*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JPetTSlot*) (soff+(sizeof(JPetTSlot)*i)))->~G__TJPetTSlot();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JPetTSlot*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JPetTSlot*) (soff))->~G__TJPetTSlot();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__JPetTSlotDict_479_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JPetTSlot* dest = (JPetTSlot*) G__getstructoffset();
   *dest = *(JPetTSlot*) libp->para[0].ref;
   const JPetTSlot& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JPetTSlot */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJPetTSlotDict {
 public:
  G__Sizep2memfuncJPetTSlotDict(): p(&G__Sizep2memfuncJPetTSlotDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJPetTSlotDict::*p)();
};

size_t G__get_sizep2memfuncJPetTSlotDict()
{
  G__Sizep2memfuncJPetTSlotDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJPetTSlotDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot))) {
     JPetTSlot *G__Lderived;
     G__Lderived=(JPetTSlot*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot),G__get_linked_tagnum(&G__JPetTSlotDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot),G__get_linked_tagnum(&G__JPetTSlotDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJPetTSlotDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<EdgeType,float>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType> >",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SingleCh>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > >",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JPetSigCh>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JPetTSlot */
static void G__setup_memvarJPetTSlot(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot));
   { JPetTSlot *p; p=(JPetTSlot*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JPetTSlotDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR),G__defined_typename("vector<JPetSigCh>"),-1,4,"fSigChannels=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJPetTSlotDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJPetTSlot(void) {
   /* JPetTSlot */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot));
   G__memfunc_setup("JPetTSlot",873,G__JPetTSlotDict_479_0_1, 105, G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JPetTSlot",873,G__JPetTSlotDict_479_0_2, 105, G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot), -1, 0, 1, 1, 1, 0, "u 'vector<JPetSigCh,allocator<JPetSigCh> >' 'vector<JPetSigCh>' 11 - new_vector", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addCh",468,G__JPetTSlotDict_479_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'JPetSigCh' - 11 - new_ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__JPetTSlotDict_479_0_4, 107, -1, G__defined_typename("size_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNumberOfSigCh",1580,G__JPetTSlotDict_479_0_5, 107, -1, G__defined_typename("size_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getSigChVect",1184,G__JPetTSlotDict_479_0_6, 117, G__get_linked_tagnum(&G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR), G__defined_typename("vector<JPetSigCh>"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__JPetTSlotDict_479_0_7, 117, G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetSigCh), -1, 1, 1, 1, 1, 9, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__JPetTSlotDict_479_0_8, 85, G__get_linked_tagnum(&G__JPetTSlotDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JPetTSlot::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__JPetTSlotDict_479_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetTSlot::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__JPetTSlotDict_479_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JPetTSlot::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__JPetTSlotDict_479_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JPetTSlot::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__JPetTSlotDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__JPetTSlotDict_479_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__JPetTSlotDict_479_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetTSlot::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__JPetTSlotDict_479_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JPetTSlot::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__JPetTSlotDict_479_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JPetTSlot::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__JPetTSlotDict_479_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JPetTSlot::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("JPetTSlot", 873, G__JPetTSlotDict_479_0_20, (int) ('i'), G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot), -1, 0, 1, 1, 1, 0, "u 'JPetTSlot' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JPetTSlot", 999, G__JPetTSlotDict_479_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__JPetTSlotDict_479_0_22, (int) ('u'), G__get_linked_tagnum(&G__JPetTSlotDictLN_JPetTSlot), -1, 1, 1, 1, 1, 0, "u 'JPetTSlot' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJPetTSlotDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJPetTSlotDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJPetTSlotDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JPetTSlotDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_JPetSigCh = { "JPetSigCh" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR = { "map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR = { "vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > >,allocator<map<JPetSigCh::EdgeType,float,less<JPetSigCh::EdgeType>,allocator<pair<const JPetSigCh::EdgeType,float> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_JPetTSlot = { "JPetTSlot" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR = { "vector<JPetSigCh,allocator<JPetSigCh> >" , 99 , -1 };
G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JPetSigCh,allocator<JPetSigCh> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJPetTSlotDict() {
  G__JPetTSlotDictLN_TClass.tagnum = -1 ;
  G__JPetTSlotDictLN_TBuffer.tagnum = -1 ;
  G__JPetTSlotDictLN_TMemberInspector.tagnum = -1 ;
  G__JPetTSlotDictLN_TObject.tagnum = -1 ;
  G__JPetTSlotDictLN_TNamed.tagnum = -1 ;
  G__JPetTSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JPetTSlotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetTSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JPetTSlotDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__JPetTSlotDictLN_JPetSigCh.tagnum = -1 ;
  G__JPetTSlotDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR.tagnum = -1 ;
  G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__JPetTSlotDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JPetTSlotDictLN_JPetTSlot.tagnum = -1 ;
  G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR.tagnum = -1 ;
  G__JPetTSlotDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJPetTSlotDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_JPetSigCh);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_JPetTSlot),sizeof(JPetTSlot),-1,62720,(char*)NULL,G__setup_memvarJPetTSlot,G__setup_memfuncJPetTSlot);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR);
   G__get_linked_tagnum_fwd(&G__JPetTSlotDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupJPetTSlotDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJPetTSlotDict()");
  G__set_cpp_environmentJPetTSlotDict();
  G__cpp_setup_tagtableJPetTSlotDict();

  G__cpp_setup_inheritanceJPetTSlotDict();

  G__cpp_setup_typetableJPetTSlotDict();

  G__cpp_setup_memvarJPetTSlotDict();

  G__cpp_setup_memfuncJPetTSlotDict();
  G__cpp_setup_globalJPetTSlotDict();
  G__cpp_setup_funcJPetTSlotDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJPetTSlotDict();
  return;
}
class G__cpp_setup_initJPetTSlotDict {
  public:
    G__cpp_setup_initJPetTSlotDict() { G__add_setup_func("JPetTSlotDict",(G__incsetup)(&G__cpp_setupJPetTSlotDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJPetTSlotDict() { G__remove_setup_func("JPetTSlotDict"); }
};
G__cpp_setup_initJPetTSlotDict G__cpp_setup_initializerJPetTSlotDict;

