/********************************************************************
* JPetTSlotDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JPetTSlotDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJPetTSlotDict();
extern void G__cpp_setup_inheritanceJPetTSlotDict();
extern void G__cpp_setup_typetableJPetTSlotDict();
extern void G__cpp_setup_memvarJPetTSlotDict();
extern void G__cpp_setup_globalJPetTSlotDict();
extern void G__cpp_setup_memfuncJPetTSlotDict();
extern void G__cpp_setup_funcJPetTSlotDict();
extern void G__set_cpp_environmentJPetTSlotDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JPetTSlot.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JPetTSlotDictLN_TClass;
extern G__linked_taginfo G__JPetTSlotDictLN_TBuffer;
extern G__linked_taginfo G__JPetTSlotDictLN_TMemberInspector;
extern G__linked_taginfo G__JPetTSlotDictLN_TObject;
extern G__linked_taginfo G__JPetTSlotDictLN_TNamed;
extern G__linked_taginfo G__JPetTSlotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetTSlotDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetTSlotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JPetTSlotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__JPetTSlotDictLN_JPetSigCh;
extern G__linked_taginfo G__JPetTSlotDictLN_maplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgR;
extern G__linked_taginfo G__JPetTSlotDictLN_vectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRcOallocatorlEmaplEJPetSigChcLcLEdgeTypecOfloatcOlesslEJPetSigChcLcLEdgeTypegRcOallocatorlEpairlEconstsPJPetSigChcLcLEdgeTypecOfloatgRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JPetTSlotDictLN_JPetTSlot;
extern G__linked_taginfo G__JPetTSlotDictLN_vectorlEJPetSigChcOallocatorlEJPetSigChgRsPgR;
extern G__linked_taginfo G__JPetTSlotDictLN_reverse_iteratorlEvectorlEJPetSigChcOallocatorlEJPetSigChgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
